# Generated by Django 6.0.3 on 2026-04-07 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trend_type', models.CharField(choices=[('hashtag', 'Hashtag'), ('sound', 'Sound')], max_length=20)),
                ('viral_score', models.FloatField(db_index=True, default=0.0)),
                ('view_count', models.BigIntegerField(default=0)),
                ('collected_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.country')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.platform')),
            ],
        ),
        migrations.CreateModel(
            name='TrendSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.BigIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('trend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='trends.trend')),
            ],
        ),
        migrations.AddIndex(
            model_name='trend',
            index=models.Index(fields=['country', 'platform', '-viral_score'], name='trends_tren_country_222929_idx'),
        ),
    ]
