# Generated by Django 6.0.3 on 2026-04-23 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='collected_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trend',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trends.country'),
        ),
        migrations.AlterField(
            model_name='trend',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trends.platform'),
        ),
        migrations.AddConstraint(
            model_name='trend',
            constraint=models.UniqueConstraint(fields=('name', 'platform', 'country', 'trend_type'), name='unique_trend'),
        ),
    ]
